spring:
  config:
    import: 
      - "classpath:defaults.yaml"
      - "classpath:anemoi-defaults.yaml"
  main:
    banner-mode: false
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
