name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: true
      matrix:
        language: [ 'java','javascript' ]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: init CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
          java-version: '17'
          distribution: 'adopt'
    
    - name: build
      run: mvn --batch-mode --update-snapshots verify

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
